### ISSUE TITLE
Component Groups

### ISSUE THREAD

**Issue by benjisoft** [ks888/LambStatus#10]
Allow grouping of components. 

E.g:
![Status Page Groups](https://3.bp.blogspot.com/-x81ymysWdlo/V0saMLgNRrI/AAAAAAAAAmw/JMKt-WrgjnwL99CQh5htxpvj-yeRnKfCQCLcB/s1600/Screen%2BShot%2B2016-05-29%2Bat%2B12.34.08%2BPM.png)

**Comment by ks888** [comment]
Thank you for opening the issue!

Yes, the grouping of the components looks necessary. [The status page of Travis CI](https://www.traviscistatus.com/) utilizes the grouping feature very well.

Now I am thinking about [the next features](https://github.com/ks888/LambStatus#todo) LambStatus will have. This issue definitely have the impact for this. If there are other features important for you, feel free to open new issues.

**Comment by benjisoft** [comment]
Merged into #14
