### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by nodomain** [ks888/LambStatus#102]
Awesome product!

I would like to see a "force HTTPs" option, e.g. that the CloudFront behavior by default is set to redirect HTTP to HTTPS. Would you please implement or give me a hint where to "fix" this? Newbie to Cloudformation...

**Comment by ks888** [comment]
Sounds good! I think we can always redirect http to https and don't need to make it optional as I assume our status page supports https access in any case.

Also, thank you for offering your help. Our cloudformation template file is `./cloudformation/lamb-status.yml` and maybe just modifying some properties of the [AWS::CloudFront::Distribution](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution.html) resource is enough. There are some [ViewerProtocolPolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-defaultcachebehavior.html#cfn-cloudfront-defaultcachebehavior-viewerprotocolpolicy) properties and so change these values seeing [this doc](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CacheBehavior.html).
