### ISSUE TITLE
Guide for custom uptime metrics

### ISSUE THREAD

**Issue by wmnnd** [ks888/LambStatus#108]
Hey there,

I’ve just [set up](https://status.dblsqd.com/) LambStatus for my application [DBLSQD](https://www.dblsqd.com) and I’m really quite impressed by this project!

I saw the discussion on issue #72 and thought there might be a compromise: Would you accept a PR that adds a guide to the LambStatus on how to implement custom serverless uptime and response time metrics with Lambda and CloudWatch? I think that would make it much easier for users who aren’t familiar with those technologies.

**Comment by ks888** [comment]
Thank you for your suggestion! Yes, I think that's an awesome idea and I will definitely accept the PR.

The project is using [GatsbyJS](https://www.gatsbyjs.org/) as the documentation tool and [this directory](https://github.com/ks888/LambStatus/tree/master/docs/content/docs) contains all the source markdown files and images.

**Comment by wmnnd** [comment]
I’ve now published a tutorial for setting up monitoring with Lambda and CloudWatch on Medium. Please let me know if you like the approach described there and if you do, I’ll adapt for the LambStatus docs and create a pull request :-)

https://medium.com/@pentacent/serverless-monitoring-of-apps-websites-with-aws-lambda-5431e6713a66

**Comment by ks888** [comment]
Awesome tutorial! I definitely want to introduce that approach in the docs!

**Comment by ks888** [comment]
Now the v0.6.2 is released and your awesome tutorial is published! Thank you!
https://lambstatus.github.io/set-up-custom-http-s-monitoring
