### ISSUE TITLE
API for adding scheduled maintenance

### ISSUE THREAD

**Issue by jaredsmith** [ks888/LambStatus#109]
Would you please consider adding an API endpoint for adding/removing scheduled maintenance?  It seems there's an endpoint for incidents and for components and for metrics, but not yet one for scheduled maintenance.

**Comment by ks888** [comment]
Thank you for suggestion! Yes, there should be the API endpoint for scheduled maintenance. I will add the feature sometime soon.

**Comment by ks888** [comment]
Now the maintenance API is available on v0.6.2.
https://lambstatus.github.io/apidocs/#maintenance
