### ISSUE TITLE
scheduled maintenance ordering

### ISSUE THREAD

**Issue by stevenolen** [ks888/LambStatus#120]
Hey! Awesome project, thank you!

I noticed when scheduling two maintenances that the ordering can feel very odd (eg. the ordering is based on the `createdAt` field, rather than the `startAt` field). The natural idea here feels like having the maintenance that is most pressing/approaching soonest should be listed first.

I don't have much experience with frontend code in order to actually make this a configurable setting, but can offer a one-line patch if this would generally useful idea:

```
diff --git a/packages/frontend/src/reducers/maintenances.js b/packages/frontend/src/reducers/maintenances.js
index 431f0e8..64e5c8f 100644
--- a/packages/frontend/src/reducers/maintenances.js
+++ b/packages/frontend/src/reducers/maintenances.js
@@ -4,7 +4,7 @@ import { LIST_MAINTENANCES, LIST_MAINTENANCE, ADD_MAINTENANCE, EDIT_MAINTENANCE,
 function listMaintenancesHandler (state = { }, action) {
   const maintenances = action.maintenances
   maintenances.sort((a, b) => {
-    return a.createdAt < b.createdAt
+    return a.startAt > b.startAt
   })

   return Object.assign({}, state, {
```

**Comment by ks888** [comment]
Thank you for your suggestion and sorry for my late reply. Yes, especially in the status page, it's better to sort the unfinished maintenance by soonest-first order. I'm not sure the best order for the admin page, though.

I've created the pull request https://github.com/ks888/LambStatus/pull/123 which:
* sorts maintenance items in the status page by the 'startAt' time
* shows the 'startAt' and 'endAt' of each maitenance item in the admin page like below
<img width="723" alt="screen shot 2018-06-01 at 18 15 23" src="https://user-images.githubusercontent.com/8448120/40834216-34af0fa6-65cb-11e8-984a-7c7fcab04679.png">

Further suggestions are welcome!

**Comment by ks888** [comment]
I believe the main ordering issue is solved, so let me close this issue.

**Comment by stevenolen** [comment]
perfect, thank you so much!!
