### ISSUE TITLE
rss feeds to include maintenances?

### ISSUE THREAD

**Issue by chenrui333** [ks888/LambStatus#127]
It is great repo, I wonder if rss feeds can include the maintenances info. 

Moreover, I am not sure whether it is a good idea to embed the maintenance information card into the incident history?

Something like this?
![twitter-api-status](https://user-images.githubusercontent.com/1580956/41867121-30ea0b60-7880-11e8-9b5b-b0b527e65c42.png)

**Comment by ks888** [comment]
Thank you for the suggestion. I guess a maintenance is included. See [the rss feed of the demo page](https://demo-status.lambstatus.org/history.rss). If it doesn't in your case, it's probably a bug and please report the details.

A maintenance information card is embedded into the history after the maintenance is completed. IMHO, it's good to show the upcoming maintenance information on the upper side of the webpage.

**Comment by chenrui333** [comment]
@ks888 I guess your rss has the maintenance page has that. But somehow, our test status check page does not show right in the rss feeds:
```
        <item>
            <title><![CDATA[Meetup Pro maintenance]]></title>
            <link>https://d3o5gfmojk05x1.cloudfront.net/incidents/tsITMTtsiZnO</link>
            <guid>https://d3o5gfmojk05x1.cloudfront.net/incidents/tsITMTtsiZnO</guid>
            <pubDate>Mon, 25 Jun 2018 17:53:31 GMT</pubDate>
            <content:encoded><![CDATA[<p><small>Jun 25, 2018, 17:53 UTC</small><br><strong>Scheduled</strong> - We will perform network maintenance. Brief customer service interruption is expected from this maintenance.</p>]]></content:encoded>
        </item>
```

You can checkout [here](https://d3o5gfmojk05x1.cloudfront.net/)

**Comment by ks888** [comment]
Oh, you mean the link `https://d3o5gfmojk05x1.cloudfront.net/incidents/tsITMTtsiZnO` is broken? OK, that's the bug and I'm going to fix it soon.

**Comment by chenrui333** [comment]
Thanks for the fix, but not quite sure about the fix for the UI change, the link looks the same?

**Comment by chenrui333** [comment]
In my previous comment, I am more curious about 
`<link>https://d3o5gfmojk05x1.cloudfront.net/incidents/tsITMTtsiZnO</link>`
should be 
`<link>https://d3o5gfmojk05x1.cloudfront.net/maintenances/tsITMTtsiZnO</link>`?

**Comment by ks888** [comment]
Yes, `<link>` tag in the rss feed is fixed.

I've just release v0.6.4 which contains this fix. Please try it out. Here is the upgrade guide: https://lambstatus.github.io/upgrading-lamb-status
