### ISSUE TITLE
SNS StatusPage-IncidentNotification not working

### ISSUE THREAD

**Issue by dakotabenjamin** [ks888/LambStatus#136]
Maybe I am using it wrong, but i have an Elastic Beanstalk app, and I set up an alarm that triggered when network usage was high. I set the Notification to StatusPage-IncidentNotification, but nothing happens when the alarm is triggered. Do I need to do anything else, or is this a bug?

**Comment by ks888** [comment]
StatusPage-IncidentNotification is the topic to send the incident email and update the rss feed. So far there is no topic to create or update the incident, though I think such an integration is nice to have.

As LambStatus has the APIs, you can write a script (or Lambda function) to integrate the alarm with LambStatus.
https://lambstatus.github.io/apidocs/#create-a-new-incident
