### ISSUE TITLE
Update current installation for admin url and SSL

### ISSUE THREAD

**Issue by rniedosmialek** [ks888/LambStatus#137]
I have built our status page site from the cloudformation script but realized I did not define the admin url and the arn for the SSL used for the admin URL. How can I update the stack or the site itself with these details I missed without destroying what I have and rebuilding again? 

The update stack operation failed and rolled back as it appears since the variables and configuration for admin URL were not present the first time that it will not apply the new one set in the update process.

**Comment by ks888** [comment]
Ummm, I suppose the admin url and SSL settings can be updated using the update stack operation. Can you share the error message when the update operation failed? The actual parameters are also helpful (of course you can mask the sensitive part).

**Comment by rniedosmialek** [comment]
I was able to update the process. The errors were related to the current role I was under.
