### ISSUE TITLE
lamb-status.yml is not updated in the s3 bucket

### ISSUE THREAD

**Issue by arunjayanth** [ks888/LambStatus#138]
Hi, 

In the github page, I can the new output additions for AdminPageCloudFrontDomainName and StatusPageCloudFrontDomainName, but the same is not found in the lamb-status.yml which is used in https://s3-ap-northeast-1.amazonaws.com/lambstatus/cf-template/0.6.4/lamb-status.yml . Please update the lamb-status.yml file in the s3 bucket.

**Comment by ks888** [comment]
Sorry for my late reply. I've just released the v0.6.5.
