### ISSUE TITLE
Add region suport sa-east-1

### ISSUE THREAD

**Issue by pexaorj** [ks888/LambStatus#158]
Hi guys,

Could you have any news about add sa-east-1 region? Or if I can use it there in another way?

**Comment by ks888** [comment]
Unfortunately sa-east-1 region is not supported yet because Amazon Cognito is not available.
https://lambstatus.github.io/supported-aws-regions
https://docs.aws.amazon.com/general/latest/gr/rande.html#cognito_identity_region
