### ISSUE TITLE
NaN on custom metrics

### ISSUE THREAD

**Issue by cxnky** [ks888/LambStatus#164]
Every minute I am posting something along the lines of 
```json
{"xxxxx":[{"timestamp":"2019-08-16T00:38Z","value":"254.4"}]}
```

but when I go onto the metrics page, it just says "NaN.00"

**Comment by cxnky** [comment]
Okay, so it appears to happen when I submit another metric?

**Comment by ks888** [comment]
Sorry for my late reply.

> Okay, so it appears to happen when I submit another metric?

I can't understand this very much. Can you share steps to reproduce the bug?

**Comment by cxnky** [comment]
No worries, so I submit ```json
{"xxxxx":[{"timestamp":"2019-08-16T00:38Z","value":"254.4"}]}
``` and it displays "254.4" for the metric, however when I post 
```json
{"xxxxx":[{"timestamp":"2019-08-16T01:38Z","value":"254.4"}]}
```, then it shows as NaN on the metric

**Comment by cxnky** [comment]
Closing this as it is obviously going no where, gonna be moving to something else.
