### ISSUE TITLE
Step 2 of npm run install brings out bunch of errors

### ISSUE THREAD

**Issue by Samueladewole** [ks888/LambStatus#168]
There is an issue with the step 2 of setup environment of this app. It brings multiple errors replicated on different machines and node versions. 

gyp ERR!

node-pre-gyp ERR!

gyp ERR! stack

npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by ks888** [comment]
Thank you for reporting the issue. I today executed `npm run install` without problems (node.js 10.16.3 and macOS Mojave). Can you share your environment details? Is there any other error message?

**Comment by Samueladewole** [comment]
Thanks for your response. I have now moved away from this project as other tools have since been adopted. 
Thanks for taking time out. 
Cheers!
Sam
