### ISSUE TITLE
Email notification to users

### ISSUE THREAD

**Issue by ks888** [ks888/LambStatus#17]
When incidents are created/updated, send the notification to users.

**Comment by ccannell** [comment]
As a workaround I am currently using [Zapier](https://zapier.com/zapbook/zaps/1441/get-rss-feed-updates-via-email/)

**Comment by flaccid** [comment]
@ks888 sorry for the ping, but just wondering if there is an ETA on this or if any work has been done yet? If not, I am consider shelling some time out as this is a must needed feature that is missing (btw fantastic work on this!).

**Comment by ks888** [comment]
Thank you for asking. I guess at least the tasks below need to be done.
* Subscribe/unsubscribe
   How should we maintain the list of email? Cognito User Pool may be good since we don't need to build the UIs to manage subscribers
* Send the emails on incident updates
   Using the SES as the sender sounds nice as the first step
* Handle notifications about bounces and complaints so that the sender reputation is not damaged
   AWS doc: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/monitor-sender-reputation.html

It seems it takes about 2 months for me. I can start to work on this next month and I'm very glad if you work on one or all of these tasks.

**Comment by tomweston** [comment]
Cant wait for notification support.. @ks888 awesome work..!

**Comment by ks888** [comment]
FYI: I've recently spent my time for the landing page and documentation. So it will take more time to complete this issue.

**Comment by kbariotis** [comment]
The only thing that worries me here is that SES requires domain verification through DKIM.

**Comment by ks888** [comment]
Now the PR is merged and the email notification will be available at the next version v0.5.2.

<img width="355" alt="screen shot 2018-02-17 at 13 41 40" src="https://user-images.githubusercontent.com/8448120/36338045-6c7437d4-13e8-11e8-92e4-19104190a845.png">

**Comment by ks888** [comment]
@kbariotis Thank you for your comment. Now the LambStatus asks admin users to verify the email address or domain and authenticate email with DKIM.
