### ISSUE TITLE
Node.js 8 is EOL

### ISSUE THREAD

**Issue by allcloud-ronen** [ks888/LambStatus#170]
Since all the Lambda functions are in Node.js 8.10 which will be EOL by the ned of the year, I wanted to know:
1. Are you going to update the functions to use Node 10.x ?
2. If I changed the existing functions to use Node 10.x on my AWS account, should it still work, or do I need to make any changes in the code?

**Comment by coltondick** [comment]
I upgraded the Lambda functions yesterday to Node 10.x by adjusting the Cloudfromation template and it's working as expected. 

You can see my changes [here ](https://github.com/coltondick/LambStatus/blob/master/cloudformation/lamb-status.yml)while we await official support.

**Comment by ks888** [comment]
Thank you for opening the issue. I updated the Node.js version to 10.x today https://github.com/ks888/LambStatus/commit/718567e73b9b1414675fbd2dec63d0750dbd9be6. The CI and some manual test indicate no problem. I'm going to release the new version tomorrow.

**Comment by ks888** [comment]
Now v0.6.6 is released. It supports `Node 10.x`.

See [the doc](https://lambstatus.github.io/upgrading-lamb-status) to upgrade the system.

**Comment by allcloud-ronen** [comment]
Thanks a lot for the fast reply.
