### ISSUE TITLE
Endpoint request timed out - 504 on /prod/external-metrics?type=CloudWatch

### ISSUE THREAD

**Issue by ajohnstone** [ks888/LambStatus#36]
Get "{"message": "Endpoint request timed out"}" every time.
504 on /prod/external-metrics?type=CloudWatch

![p3ooyd2](https://cloud.githubusercontent.com/assets/173567/26525018/cff508ca-4340-11e7-9e27-937aa53ec8db.png)

**Comment by ks888** [comment]
Thank you for creating the PR. I've merged it. Increasing the MemorySize and Timeout is the good workaround, but we may need to increase them again if someone has the larger number of metrics.

So far the GET external-metrics API returns all the metrics. That's the problem. I will let the API support the pagination.
