### ISSUE TITLE
LambStatus API to post the metric data

### ISSUE THREAD

**Issue by ks888** [ks888/LambStatus#44]
From @ccannell's comment on gitter:

Christopher Cannell @ccannell 05:33
I've deployed LambStatus and now I'm a bit lost on the next step. I'd like to check an HTTP server status regularly. What is the best way to approach that? Is there documentation on the LambStatus API? Should I run a periodic lambda to poll my HTTP server and then post to LambStatus API on changes?

Kishin Yagami @ks888 10:42
Thank you for asking. Since LambStatus has few features for monitoring the service, such as alarm, it's better to post your server's status to your monitoring service at first. Then, integrate the monitoring service with LambStatus. If your monitoring service is CloudWatch, the integration is easy. If not, it is harder because there is no LambStatus API to post the data.
LambStatus API to post the data sounds nice. Maybe it's better to support it.

**Comment by ccannell** [comment]
This could be useful for a couple of reasons.

1. If you have a Lambda monitoring some resource, you could POST the data directly without outputing to CloudWatch, setting up a metric filter, and then setting up LambStatus to look for the metric.

2. Save cost. CloudWatch metric filters and logs all cost money.

**Comment by ks888** [comment]
Currently working on this issue.

TODO:
* [ ] Support API Token https://github.com/ks888/LambStatus/issues/46
* [ ] Add API to post the metric data
* [ ] Use the new API  in the CloudWatch integration 
* [ ] Add the document to explain the usage of the API

**Comment by ks888** [comment]
Now API to post the metric data is supported. Will be available after v0.4.0.
Docs: https://github.com/ks888/LambStatus/wiki/LambStatus-API-v0
