### ISSUE TITLE
[Metrics] Add an option to choose the statistics

### ISSUE THREAD

**Issue by ks888** [ks888/LambStatus#49]
From @stephencornelius' comment on gitter:

stephencornelius @stephencornelius Jul 14 19:36
Hi, ive just setup lambstatus and really liking it so far, very easy to get working. However I’ve got a question about metrics, im adding cloudwatch metrics and was wondering if theres anyway to specify the statistic? e.g. for ELB 2xx status code the only statistic that makes sense is sum, all others just report 1, im guessing average is chosen by default?

Kishin Yagami @ks888 22:53
@stephencornelius Thank you for using LambStatus. You're right. On collecting the datapoints from CloudWatch, 'Average' statistic is used. Unfortunately there is no option to choose the other statistics. I guess it is better to add an option to choose them.

**Comment by stephencornelius** [comment]
many thanks for picking up the issue

**Comment by ks888** [comment]
I've added the statistics selector to the Metric dialog. It is available since v0.4.0 I've just released.
<img width="549" alt="screen shot 2017-08-13 at 21 35 21" src="https://user-images.githubusercontent.com/8448120/29249677-57c542d6-806f-11e7-9d95-880da3228905.png">

**Comment by stephencornelius** [comment]
Sorry ive only just been able to update our status page. this works great and now allows us to display the stats we need to.

many thanks for getting it implemented so quickly
