### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by networkdawg** [ks888/LambStatus#50]
Hello,

When adding a Service Name on the settings page, it combines whatever you enter there with the green Status text. I.E. My AWS MonitoringStatus . There needs to be a space between the service name entered and the word Status.

The other thing, is when adding scheduled Maintenance. The word currently shown on the Status page is Maintenances. It should say Maintenance.

Nothing huge, but it helps with the presentation :)

**Comment by ks888** [comment]
Thank you for your suggestions. Certainly it's better if we have a space after the service name.

Oh, you mean the word `Maintenace` should be `Maintenace` even if there are multiple maintenance items? I'm confused at first, and so checked the status page of StatusPage.io. The screenshot below is from StatusPage.io, and the title is `Scheduled Maintenance` even though there are multiple items!

<img width="902" alt="screen shot 2017-07-22 at 9 57 31" src="https://user-images.githubusercontent.com/8448120/28487028-396836ac-6ec4-11e7-98da-b99b35008c6f.png">

I'm not very sure why `Maitenance` is better, but it must be correct.

**Comment by skyzyx** [comment]
“Maintenance” is one of those weird English words that uses the same form for both singular and plural.

**Comment by ks888** [comment]
I see. I'm not native English speaker, so this kind of suggestions are very helpful!

**Comment by ks888** [comment]
Thanks again for your suggestions. The fix is available since v0.4.0 I've just released.
