### ISSUE TITLE
Ability to edit Incident timeline

### ISSUE THREAD

**Issue by ryangravetteadmin** [ks888/LambStatus#56]
As a Status Admin I want the ability to edit incident timelines so that I can make updates to the timeline notes (Like inaccurate spelling or updates on a url) without having to delete the entire incident.

**Comment by ks888** [comment]
@ryangravetteadmin It sounds nice! Are you able to contribute a PR? I have several things going on, so it may take a while to get implemented.

**Comment by ks888** [comment]
Thank you! I've recently updated the [CONTRIBUTING.md](https://github.com/ks888/LambStatus/blob/master/CONTRIBUTING.md) and steps to set up the local environment gets clearer. Try it out!

**Comment by ks888** [comment]
I've fixed this issue and it's available since v0.4.1.

To edit the timeline, click the 'edit' icon on the right side:
<img width="568" alt="screen shot 2017-10-12 at 23 16 19" src="https://user-images.githubusercontent.com/8448120/31500820-772ee060-afa3-11e7-9520-471f7b7e2355.png">
