### ISSUE TITLE
Hide empty incident cards

### ISSUE THREAD

**Issue by jpike88** [ks888/LambStatus#73]
This looks ugly:

![screen shot 2017-11-25 at 3 28 25 pm](https://user-images.githubusercontent.com/9585787/33228766-4f26bf56-d1f5-11e7-9c4a-3e8012ad3a12.png)

**Comment by ks888** [comment]
Hmm, it could be. How can we improve this?

**Comment by ks888** [comment]
Is it better to show some message? Here is the example of statuspage.io.
<img width="897" alt="screen shot 2017-11-26 at 18 19 22" src="https://user-images.githubusercontent.com/8448120/33238711-73ef0802-d2d6-11e7-97d7-691ff9842858.png">

**Comment by jpike88** [comment]
Perhaps consolidate them into a single card:

Nov 21 2017 - Nov 26 2017

**Comment by jpike88** [comment]
Or just add the message, but remove each of the card borders so it looks just like statuspage.io
