### ISSUE TITLE
Broken on latest commit

### ISSUE THREAD

**Issue by jpike88** [ks888/LambStatus#78]
Settings page is breaking showing:

![screen shot 2017-11-26 at 6 37 41 pm](https://user-images.githubusercontent.com/9585787/33239650-eac33352-d2d8-11e7-804e-0a9297c75eba.png)

And status page is stuck on fetching data. It looks like the get-settings and get-public-settings functions are both not working properly

Settings table in DynamoDB just contains this (not sure if good or bad):

![screen shot 2017-11-26 at 6 33 53 pm](https://user-images.githubusercontent.com/9585787/33239627-66e61c2a-d2d8-11e7-89ca-eda477c37524.png)

Logs say this for /aws/lambda/myapp-GetSettings in CloudWatch

![screen shot 2017-11-26 at 6 34 57 pm](https://user-images.githubusercontent.com/9585787/33239636-89e25b26-d2d8-11e7-95d7-21085340f083.png)

Logs say this for /aws/lambda/myapp-GetPublicSettings in CloudWatch

![screen shot 2017-11-26 at 6 36 18 pm](https://user-images.githubusercontent.com/9585787/33239642-bc4ea952-d2d8-11e7-8d6d-64693fdbde59.png)

Because the code is minified and web packed etc, no idea how to begin to fix this myself. You may need to provide some info on how to load up the lambda projects and debug them etc as I don't know how to set up a similar development workflow

**Comment by ks888** [comment]
Sorry for confusing you. The CloudFormation template on latest commit sometimes doesn't work well. The frontend codes are copied from existing S3 bucket, which doesn't always up to date ([here is the corresponding code](https://github.com/ks888/LambStatus/blob/master/cloudformation/lamb-status.yml#L3964)). The lambda functions have the same issue ([here is the code](https://github.com/ks888/LambStatus/blob/master/cloudformation/lamb-status.yml#L3964)). 

To try out the latest commit, so far it is best to follow [this guide for contributors](https://github.com/ks888/LambStatus/blob/master/CONTRIBUTING.md).

**Comment by jpike88** [comment]
Ahh thanks a lot!
