### ISSUE TITLE
Event model?

### ISSUE THREAD

**Issue by sime** [ks888/LambStatus#83]
Hi!

I'm really interested in LambStatus, particularly because all of our applications are using the serverless framework.

Nonetheless, I feel like LambStatus could use an "Event" model. e.g. A client would ping the Event API at the end of a successful deployment.

Currently we are doing this with Cachet as a "incident". Though to my eyes, a deployment is not an incident.

The bigger question is are status pages meant to be a repository of events? Taking a quick look around at the public status pages, no one seems to be doing this.

**Comment by ks888** [comment]
Hi, thank you for your interest!

I'm not very sure I understand your comments correctly, so let me ask
questions. Do you want to show a list of events in your status page? If so,
why do you want to do that? You gave me 'the end of deployment' as the
example, but I'm not sure why you want to show that.

Specific uae case might be helpful!




2018/01/06 23:08 "Simon Males" <notifications@github.com>:

**Comment by sime** [comment]
If for example response times are increasing of an web application, usually I want to know when the latest deployment was.

**Comment by ks888** [comment]
Hmm I see. How about using metrics API? You can send a datapoint to the
metric via the API when some event like deployment happens. By checking the
metrics graph, you will know when the deployment happened immediately. Here
is the docs:
https://lambstatus.github.io/integrate-with-other-monitoring-systems

2018/01/07 0:34 "Simon Males" <notifications@github.com>:

**Comment by sime** [comment]
I know what you mean, but Metrics are not noisy enough in my mind to represent a deployment. Possible makes sense when there are 2-3 deployments a day.

Cheers!
