### ISSUE TITLE
Show the uptime percentage by component

### ISSUE THREAD

**Issue by ks888** [ks888/LambStatus#88]
Feature suggestion from @GustavoEsser:

Show the uptime percentage of components. Maybe the view like the screenshot below looks good.
<img width="861" alt="screen shot 2018-01-18 at 23 29 18" src="https://user-images.githubusercontent.com/8448120/35102836-6ea35bbe-fca7-11e7-9ef1-b00c5fb0e1ed.png">

**Comment by GustavoEsser** [comment]
Hello,
Perfect, What is the status ?

**Comment by ks888** [comment]
Had the same request from @chenrui333 at gitter.

**Comment by chenrui333** [comment]
yeah, that would be a cool feature.

**Comment by ashishxooa** [comment]
Is this feature expected to drop anytime soon?

**Comment by GustavoEsser** [comment]
Still has forecast of this feature ?

**Comment by ks888** [comment]
Sorry, I have no plan to support this feature and so let me close this issue.
If someone is going to support this, feel free to reopen it.
