### ISSUE TITLE
Upgrade (to 0.6.0) loses custom SSL and CNAMEs

### ISSUE THREAD

**Issue by chris-scentregroup** [ks888/LambStatus#96]
Carried out an upgrade, observed the following which I fixed by hand:

- add back custom ssl cert usage (select my cert again)
- add back Alternate Domain Names (CNAMEs)

Might indicate that we need these as params to provide in the first setup or later to modify in the stack. Apologies if this is already supported and documented.

**Comment by ks888** [comment]
Sorry for inconvenience. The CloudFront distribution resource is created by the CloudFormation. When the resource is updated by the CloudFormation, the settings described in the CloudFormation template is only considered and the fixes by hand are overwritten.

Fortunately LambStatus already supports the custom domain. See [this document page](https://lambstatus.github.io/set-up-custom-domain), and try to upgrade the stack again!

**Comment by chris-scentregroup** [comment]
Actioned the upgrade and it appears successful! Thank you. Issue in #95 was not resolved in turn however (we'll keep that issue open).
